## Second Model: Logistic Regression

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, RocCurveDisplay, ConfusionMatrixDisplay
from sklearn.datasets import load_iris

%matplotlib inline

In [2]:
#Load in the dataset
diabetes_df = pd.read_csv('cleaned_diabetes_data.csv', index_col=0)

In [3]:
diabetes_df

race  gender      age  admission_type_id  \
0             Caucasian  Female   [0-10)                  6   
1             Caucasian  Female  [10-20)                  1   
2       AfricanAmerican  Female  [20-30)                  1   
3             Caucasian    Male  [30-40)                  1   
4             Caucasian    Male  [40-50)                  1   
...                 ...     ...      ...                ...   
101754        Caucasian  Female  [70-80)                  1   
101755            Other  Female  [40-50)                  1   
101756            Other  Female  [60-70)                  1   
101758        Caucasian  Female  [80-90)                  1   
101765        Caucasian    Male  [70-80)                  1   

        discharge_disposition_id  admission_source_id  time_in_hospital  \
0                             25                    1                 1   
1                              1                    7                 3   
2                              1                    7                 2   
3                              1                    7                 2   
4                              1                    7                 1   
...                          ...                  ...               ...   
101754                         1                    7                 9   
101755                         1                    7                14   
101756                         1                    7                 2   
101758                         1                    7                 5   
101765                         1                    7                 6   

       payer_code         medical_specialty  num_lab_procedures  ...  \
0         Unknown  Pediatrics-Endocrinology                  41  ...   
1         Unknown                   Unknown                  59  ...   
2         Unknown                   Unknown                  11  ...   
3         Unknown                   Unknown                  44  ...   
4         Unknown                   Unknown                  51  ...   
...           ...                       ...                 ...  ...   
101754    Unknown                   Unknown                  50  ...   
101755         MD                   Unknown                  73  ...   
101756         MD                   Unknown                  46  ...   
101758         MC                   Unknown                  76  ...   
101765    Unknown                   Unknown                  13  ...   

        citoglipton  insulin  glyburide-metformin  glipizide-metformin  \
0                No       No                   No                   No   
1                No       Up                   No                   No   
2                No       No                   No                   No   
3                No       Up                   No                   No   
4                No   Steady                   No                   No   
...             ...      ...                  ...                  ...   
101754           No   Steady                   No                   No   
101755           No       Up                   No                   No   
101756           No   Steady                   No                   No   
101758           No       Up                   No                   No   
101765           No       No                   No                   No   

        glimepiride-pioglitazone metformin-rosiglitazone  \
0                             No                      No   
1                             No                      No   
2                             No                      No   
3                             No                      No   
4                             No                      No   
...                          ...                     ...   
101754                        No                      No   
101755                        No                      No   
101756                        No                      No   
101758 

## Preprocessing and Encoding the Data

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# train test split
from sklearn.model_selection import train_test_split

# preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

# model validation: testing model variance with cross validation
from sklearn.model_selection import KFold, cross_val_score, cross_validate, ShuffleSplit

#Feature Selection
X = diabetes_df.drop(['readmitted'], axis=1)
y= diabetes_df['readmitted']

#Label encode target variable 'y' into numerics
labenc = LabelEncoder()
y = labenc.fit_transform(y)



In [5]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, random_state = 42)

In [6]:
X_train.columns

Index(['race', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'payer_code', 'medical_specialty', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed'],
      dtype='object')

In [7]:
def encode_and_concat_feature(X, feature_name, ohe):
    """
    Helper function for transforming a feature into multiple columns of 1s and 0s. Used
    in both training and testing steps.  Takes in the full X dataframe, feature name, 
    and encoder, and returns the dataframe with that feature transformed into multiple
    columns of 1s and 0s
    """
    # create new one-hot encoded df based on the feature
    single_feature_df = X[[feature_name]]
    feature_array = ohe.transform(single_feature_df).toarray()
    
    #create unique column names by prefixing with feature name
    ohe_column_names = [f'{feature_name}_{category}' for category in ohe.categories_[0]]
    ohe_df = pd.DataFrame(feature_array, columns=ohe_column_names, index=X.index)

    # drop the old feature from X and concat the new one-hot encoded df
    X = X.drop(feature_name, axis=1)
    X = pd.concat([X, ohe_df], axis=1)
    
    return X

In [8]:
def encode_and_concat_feature_train(X_train, feature_name):
    """
    Helper function for transforming training data.  It takes in the full X dataframe and
    feature name, makes a one-hot encoder, and returns the encoder as well as the dataframe
    with that feature transformed into multiple columns of 1s and 0s
    """
    # make a one-hot encoder and fit it to the training data
    ohe = OneHotEncoder(categories="auto", handle_unknown="ignore")
    single_feature_df = X_train[[feature_name]]
    ohe.fit(single_feature_df)
    
    # call helper function that actually encodes the feature and concats it
    X_train = encode_and_concat_feature(X_train, feature_name, ohe)
    
    return ohe, X_train

In [9]:
categorical_feature_names = ['race', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id','payer_code', 'medical_specialty','diag_1', 'diag_2', 'diag_3','max_glu_serum', 'A1Cresult', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide','citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed']

encoders = {}

#Encode X_train and store encoders
for categorical_feature in categorical_feature_names:
    ohe,X_train = encode_and_concat_feature_train(X_train, categorical_feature)
    encoders[categorical_feature] = ohe

In [10]:
encoders

{'race': OneHotEncoder(handle_unknown='ignore'),
 'gender': OneHotEncoder(handle_unknown='ignore'),
 'age': OneHotEncoder(handle_unknown='ignore'),
 'admission_type_id': OneHotEncoder(handle_unknown='ignore'),
 'discharge_disposition_id': OneHotEncoder(handle_unknown='ignore'),
 'admission_source_id': OneHotEncoder(handle_unknown='ignore'),
 'payer_code': OneHotEncoder(handle_unknown='ignore'),
 'medical_specialty': OneHotEncoder(handle_unknown='ignore'),
 'diag_1': OneHotEncoder(handle_unknown='ignore'),
 'diag_2': OneHotEncoder(handle_unknown='ignore'),
 'diag_3': OneHotEncoder(handle_unknown='ignore'),
 'max_glu_serum': OneHotEncoder(handle_unknown='ignore'),
 'A1Cresult': OneHotEncoder(handle_unknown='ignore'),
 'metformin': OneHotEncoder(handle_unknown='ignore'),
 'repaglinide': OneHotEncoder(handle_unknown='ignore'),
 'nateglinide': OneHotEncoder(handle_unknown='ignore'),
 'chlorpropamide': OneHotEncoder(handle_unknown='ignore'),
 'glimepiride': OneHotEncoder(handle_unknown='igno

In [11]:
def encode_and_concat_feature_test(X_test, feature_name, ohe):
    """
    Helper function for transforming test data. It takes in the full X_test dataframe,
    the feature name, and the already fitted encoder from X_train. Returns the transformed
    X_test with that feature encoded into multiple columns of 1s and 0s.
    """
    #Create new one-hot encoded df for the feature using the fitted encoder from X_train
    single_feature_df = X_test[[feature_name]]
    feature_array = ohe.transform(single_feature_df).toarray()

    #Ensure column names have same prefix structure as in X train
    ohe_column_names = [f'{feature_name}_{category}' for category in ohe.categories_[0]]
    ohe_df = pd.DataFrame(feature_array, columns = ohe_column_names, index=X_test.index)

    #Drop the old feature from X_test and concat the new one-hot encoded df
    X_test = X_test.drop(feature_name, axis=1)
    X_test = pd.concat([X_test, ohe_df], axis=1)
    
    return X_test

# Encode X_test using the fitted encoders
for categorical_feature in categorical_feature_names:
    X_test = encode_and_concat_feature_test(X_test, categorical_feature, encoders[categorical_feature])


In [12]:
# Check encoding
X_train

time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
29262                 1                  36               1               24   
54052                 8                  49               0               10   
93790                 3                   4               0               20   
66811                 2                  53               0               12   
6103                  5                  44               4               49   
...                 ...                 ...             ...              ...   
49643                 1                   3               0                7   
7670                  9                  48               6               33   
77026                 6                  29               1               14   
921                   7                  69               1               23   
21227                 2                  60               0               12   

       number_outpatient  number_emergency  number_inpatient  \
29262                  0                 0                 1   
54052                  1                 0                 0   
93790                  2                 0                 1   
66811                  0                 0                 0   
6103                   0                 0                 0   
...                  ...               ...               ...   
49643                  0                 0                 0   
7670                   0                 0                 0   
77026                  0                 0                 0   
921                    0                 0                 0   
21227                  0                 0                 0   

       number_diagnoses  race_AfricanAmerican  race_Asian  ...  \
29262                 4                   0.0         0.0  ...   
54052                 5                   0.0         0.0  ...   
93790                 9                   0.0         0.0  ...   
66811                 6                   1.0         0.0  ...   
6103                  9                   0.0         0.0  ...   
...                 ...                   ...         ...  ...   
49643                 9                   0.0         0.0  ...   
7670                  8                   0.0         0.0  ...   
77026                 4                   0.0         0.0  ...   
921                   9                   1.0         0.0  ...   
21227                 7                   0.0         0.0  ...   

       glipizide-metformin_No  glipizide-metformin_Steady  \
29262                     1.0                         0.0   
54052                     1.0                         0.0   
93790                     1.0                         0.0   
66811                     1.0                         0.0   
6103                      1.0                         0.0   
...                       ...                         ...   
49643                     1.0                         0.0   
7670                      1.0                         0.0   
77026                     1.0                         0.0   
921                       1.0                         0.0   
21227                     1.0                         0.0   

       glimepiride-pioglitazone_No  metformin-rosiglitazone_No  \
29262                          1.0                         1.0   
54052                          1.0                         1.0   
93790                          1.0                         1.0   
66811                          1.0                         1.0   
6103                           1.0                         1.0   
...                            ...                         ...   
49643                          1.0                         1.0   
7670                           1.0                         1.0   
77026                          1.0                         1.0   
921                            1.0                         1.0   
21227                    

In [13]:
X_test

time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
80578                 6                  60               2               21   
60241                 2                  32               4               13   
68768                 2                  20               0               12   
47021                 4                  35               0               21   
80121                 4                  67               0               12   
...                 ...                 ...             ...              ...   
6829                  7                  42               3               20   
46177                 6                  18               2               16   
16916                 2                  40               2               10   
64743                 3                   9               0               18   
18846                 1                  55               0                7   

       number_outpatient  number_emergency  number_inpatient  \
80578                  1                 0                 0   
60241                  0                 0                 0   
68768                  0                 0                 0   
47021                  0                 0                 0   
80121                  1                 0                 0   
...                  ...               ...               ...   
6829                   0                 0                 0   
46177                  0                 0                 0   
16916                  0                 0                 0   
64743                 42                 0                 0   
18846                  0                 0                 0   

       number_diagnoses  race_AfricanAmerican  race_Asian  ...  \
80578                 9                   0.0         0.0  ...   
60241                 9                   1.0         0.0  ...   
68768                 5                   0.0         0.0  ...   
47021                 5                   1.0         0.0  ...   
80121                 7                   0.0         0.0  ...   
...                 ...                   ...         ...  ...   
6829                  6                   0.0         0.0  ...   
46177                 9                   0.0         0.0  ...   
16916                 9                   0.0         0.0  ...   
64743                 9                   0.0         0.0  ...   
18846                 1                   0.0         0.0  ...   

       glipizide-metformin_No  glipizide-metformin_Steady  \
80578                     1.0                         0.0   
60241                     1.0                         0.0   
68768                     1.0                         0.0   
47021                     1.0                         0.0   
80121                     1.0                         0.0   
...                       ...                         ...   
6829                      1.0                         0.0   
46177                     1.0                         0.0   
16916                     1.0                         0.0   
64743                     1.0                         0.0   
18846                     1.0                         0.0   

       glimepiride-pioglitazone_No  metformin-rosiglitazone_No  \
80578                          1.0                         1.0   
60241                          1.0                         1.0   
68768                          1.0                         1.0   
47021                          1.0                         1.0   
80121                          1.0                         1.0   
...                            ...                         ...   
6829                           1.0                         1.0   
46177                          1.0                         1.0   
16916                          1.0                         1.0   
64743                          1.0                         1.0   
18846                    

In [14]:
y_train

array([1, 1, 1, ..., 1, 1, 1])

In [15]:
y_test

array([1, 1, 1, ..., 1, 1, 1])

In [16]:
X_train.shape, X_test.shape

((52479, 2312), (17494, 2312))

## Cross Validation

We need to scale the features before regularization

In [31]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)

X_test_scaled = scaler.transform(X_test)



In [33]:
# initialize the model: saga improves is optimal for large datasets

model = LogisticRegression(penalty='l2', class_weight='balanced', solver='lbfgs', max_iter=1000)

# fit the scaled training data to the model
#
model.fit(X_train_scaled, y_train)


LogisticRegression(class_weight='balanced', max_iter=1000)

In [34]:
model.score(X_train_scaled,y_train)

0.6788810762400198

In [35]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

skf = StratifiedKFold(n_splits=3)
cross_val_score(model, X_train_scaled, y_train, cv=skf, n_jobs=-1)


array([0.65792031, 0.65174641, 0.66735266])

## Initial Model Evaluation

In [21]:
model.coef_

array([[-0.04642567, -0.09704374,  0.01615417, ...,  0.24749411,
         0.43114666,  0.11067485]])

In [22]:
model.intercept_

array([0.90949391])

In [36]:
y_pred = model.predict(X_test_scaled)
y_pred

array([0, 1, 0, ..., 1, 0, 1])

In [24]:
accuracy_score(y_test, y_pred)

0.6607408254258603

In [37]:
#Class probabilities
model.predict_proba(X_test_scaled)

array([[0.58659082, 0.41340918],
       [0.3120556 , 0.6879444 ],
       [0.5397226 , 0.4602774 ],
       ...,
       [0.48708435, 0.51291565],
       [0.77018986, 0.22981014],
       [0.48729597, 0.51270403]])

## Lasso Regression

In [30]:
from sklearn.linear_model import Lasso

lasso_model = Lasso(alpha=.000001, random_state=42,  max_iter = 1000)
lasso_model.fit(X_train, y_train)

/opt/anaconda3/envs/diabetes_env/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.742e+02, tolerance: 4.251e-01
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=1e-06, random_state=42)

In [29]:
lasso_model.score(X_train,y_train)

0.06510019091927732

## Tuning

### Minority Class OverSampling with SMOTEN

In [49]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install imbalanced-learn

from imblearn.over_sampling import SMOTE


In [50]:
from imblearn.over_sampling import SMOTEN

sm=SMOTEN(sampling_strategy='minority',random_state=42,n_jobs=-1)

X_res, y_res = sm.fit_resample(X_train, y_train)

/opt/anaconda3/envs/diabetes_env/lib/python3.12/site-packages/imblearn/over_sampling/_smote/base.py:992: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(


KeyboardInterrupt: 

In [39]:
# Select important features based on feature importance
important_features = [0, 1, 2, 3, 6, 7, 35, 50, 78]  

#subset important features  
X_train_important = X_train[important_features]
X_test_important = X_test[important_features]


In [42]:
X_train_important.shape

(9, 2312)

In [47]:
y_train.shape

(52479,)

In [43]:
#Rescale the data
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train_imp_scaled = ss.fit_transform(X_train_important)
X_test_imp_scaled = ss.transform(X_test_important)

In [44]:

model_reduced = LogisticRegression(penalty='l2', class_weight='balanced', solver='lbfgs', max_iter=1000)

# fit the scaled training data to the model
#
model_reduced.fit(X_train_imp_scaled, y_train)


ValueError: Found input variables with inconsistent numbers of samples: [9, 52479]